import { StockRecord, CrisisRecord } from '../types/dashboard';

export const mockStockData: StockRecord[] = [
  {
    Date: '2023-10-27',
    AgencyName: 'Ludhiana Gas Service',
    DomesticClosingStock: 150,
    DomesticBacklog: 20,
    CommercialClosingStock: 45,
    IndustrialClosingStock47_5: 10,
    IndustrialClosingStock425: 5,
  },
  {
    Date: '2023-10-27',
    AgencyName: 'Dugri HP Gas',
    DomesticClosingStock: 80,
    DomesticBacklog: 35,
    CommercialClosingStock: 20,
    IndustrialClosingStock47_5: 5,
    IndustrialClosingStock425: 0,
  },
  {
    Date: '2023-10-27',
    AgencyName: 'Gill Gas Agency',
    DomesticClosingStock: 210,
    DomesticBacklog: 10,
    CommercialClosingStock: 55,
    IndustrialClosingStock47_5: 15,
    IndustrialClosingStock425: 8,
  },
  {
    Date: '2023-10-27',
    AgencyName: 'Model Town Indane',
    DomesticClosingStock: 120,
    DomesticBacklog: 45,
    CommercialClosingStock: 30,
    IndustrialClosingStock47_5: 8,
    IndustrialClosingStock425: 2,
  },
  {
    Date: '2023-10-27',
    AgencyName: 'Sarabha Nagar BPCL',
    DomesticClosingStock: 190,
    DomesticBacklog: 5,
    CommercialClosingStock: 50,
    IndustrialClosingStock47_5: 12,
    IndustrialClosingStock425: 6,
  },
  {
    Date: '2023-10-27',
    AgencyName: 'Civil Lines Gas',
    DomesticClosingStock: 100,
    DomesticBacklog: 50,
    CommercialClosingStock: 25,
    IndustrialClosingStock47_5: 4,
    IndustrialClosingStock425: 1,
  },
  {
    Date: '2023-10-27',
    AgencyName: 'Aggar Nagar Service',
    DomesticClosingStock: 170,
    DomesticBacklog: 15,
    CommercialClosingStock: 40,
    IndustrialClosingStock47_5: 9,
    IndustrialClosingStock425: 4,
  },
  {
    Date: '2023-10-27',
    AgencyName: 'Feroze Gandhi Indane',
    DomesticClosingStock: 60,
    DomesticBacklog: 60,
    CommercialClosingStock: 15,
    IndustrialClosingStock47_5: 2,
    IndustrialClosingStock425: 0,
  },
  {
    Date: '2023-10-27',
    AgencyName: 'BRS Nagar HPCL',
    DomesticClosingStock: 140,
    DomesticBacklog: 25,
    CommercialClosingStock: 35,
    IndustrialClosingStock47_5: 7,
    IndustrialClosingStock425: 3,
  },
  {
    Date: '2023-10-27',
    AgencyName: 'Haibowal Gas Agency',
    DomesticClosingStock: 220,
    DomesticBacklog: 8,
    CommercialClosingStock: 60,
    IndustrialClosingStock47_5: 20,
    IndustrialClosingStock425: 10,
  },
  {
    Date: '2023-10-27',
    AgencyName: 'Shimlapuri Indane',
    DomesticClosingStock: 90,
    DomesticBacklog: 40,
    CommercialClosingStock: 22,
    IndustrialClosingStock47_5: 6,
    IndustrialClosingStock425: 1,
  },
];

export const mockCrisisData: CrisisRecord[] = [
  {
    RequestID: 'REQ-001',
    ConsumerName: 'Rahul Singh',
    Category: 'Domestic',
    AgencyName: 'Ludhiana Gas Service',
    Issue: 'Shortage',
    CurrentStatus: 'Resolved',
  },
  {
    RequestID: 'REQ-002',
    ConsumerName: 'Grand Plaza Hotel',
    Category: 'Commercial',
    AgencyName: 'Dugri HP Gas',
    Issue: 'Shortage',
    CurrentStatus: 'Pending',
  },
  {
    RequestID: 'REQ-003',
    ConsumerName: 'Ludhiana Heart Center',
    Category: 'Health',
    AgencyName: 'Gill Gas Agency',
    Issue: 'Complaint',
    CurrentStatus: 'In-Progress',
  },
  {
    RequestID: 'REQ-004',
    ConsumerName: 'Priya Sharma',
    Category: 'Domestic',
    AgencyName: 'Model Town Indane',
    Issue: 'Querry',
    CurrentStatus: 'Resolved',
  },
  {
    RequestID: 'REQ-005',
    ConsumerName: 'Steel Works Ltd',
    Category: 'Commercial',
    AgencyName: 'Sarabha Nagar BPCL',
    Issue: 'Shortage',
    CurrentStatus: 'Pending',
  },
  {
    RequestID: 'REQ-006',
    ConsumerName: 'Amit Mehra',
    Category: 'Domestic',
    AgencyName: 'Civil Lines Gas',
    Issue: 'Complaint',
    CurrentStatus: 'Resolved',
  },
  {
    RequestID: 'REQ-007',
    ConsumerName: 'City Hospital',
    Category: 'Health',
    AgencyName: 'Aggar Nagar Service',
    Issue: 'Shortage',
    CurrentStatus: 'Resolved',
  },
  {
    RequestID: 'REQ-008',
    ConsumerName: 'Fast Foods Inc',
    Category: 'Commercial',
    AgencyName: 'Feroze Gandhi Indane',
    Issue: 'Complaint',
    CurrentStatus: 'In-Progress',
  },
  {
    RequestID: 'REQ-009',
    ConsumerName: 'Deepak Kumar',
    Category: 'Domestic',
    AgencyName: 'BRS Nagar HPCL',
    Issue: 'Querry',
    CurrentStatus: 'Pending',
  },
  {
    RequestID: 'REQ-010',
    ConsumerName: 'Ludhiana University',
    Category: 'Commercial',
    AgencyName: 'Haibowal Gas Agency',
    Issue: 'Shortage',
    CurrentStatus: 'Resolved',
  },
];
